### ISSUE TITLE
Arrow control of dropdowns

### ISSUE THREAD

**Issue by bumbeishvili** [bumbeishvili/webgl-globe-sunny-fivr#2]
@KetiBochorishvili 

კლავიატურაზე მარჯვენა ან მარცხენა კლავიშს რომ დააჭერს უნდა ამოიცვალოს ეს მონაცემები შესაბამისად. თუ გინდა იმ ყოველ ხუთ წამში ცვლილების ნაცვლად ეს გააკეთე (საბოლოოდ მაინც გასაკეთებელია ეს და პირდაპირ ამით დაიწყო სჯობს)

![image](https://user-images.githubusercontent.com/6873202/168344374-d6dd5f4f-0e1d-4d16-9506-9757c126e2c4.png)

![Screenshot 2022-05-13 at 22 22 00](https://user-images.githubusercontent.com/6873202/168344475-1060c7a6-fefc-4949-b027-406fa38a1cb1.png)

**Comment by KetiBochorishvili** [comment]
კარგია, ამას ვცდი, ახლა დავჯექი სამუშაოდ. 

შესაბამისად ანუ არჩეულის შემდეგის ან წინას არჩევა მოხდეს დაჭერით და სელექტშიც გამოჩნდეს ეს ახალი არჩეული ხო?

**Comment by bumbeishvili** [comment]
ჰო, უფრო ადვილი რომ იყოს მონაცემებზე გადასვლა, ფერებზეც გააკეთე იგივე, ოღონდ ზემოთა და ქვემოთა ღილაკით.

უფრო სწორად სჯობს მარჯვენა მარცხენა ფერებზე გააკეთო, ზემოთა ქვემოთა data-ზე

**Comment by bumbeishvili** [comment]
არაფერი ჭამო სანამ აკეთებ, ეგრე გავსუქდი მე ღამე მუშაობით და ტკბილეულის ჭამით :დ

**Comment by KetiBochorishvili** [comment]
:დდდდ მუშაობის დროს ვერ ვჭამ, უფრო სწორად ჭამის დროს ვერ ვაზროვნებ. :დ

ზოგადად სახლში ჩაჯდომა ასუქებს, ესეთი სამუშაო კარგად უწყობს ხელს ორივეს.

**Comment by bumbeishvili** [comment]
ჰო :/ ამ სასიარულო ბილიკის იმედი მაქვს მე

თვეში 1 კგ დაკლების ტენდენცია მაქვს :დ 

![image](https://user-images.githubusercontent.com/6873202/168358969-39bf68cd-fc0c-4414-aab4-ab20266105a2.png)

**Comment by KetiBochorishvili** [comment]
ეს შენი წონაა? იმედისმომცემი მიმართულებაა. 

მე მუზას ველოდები :დ

**Comment by bumbeishvili** [comment]
ხო ჩემია : ქვემოთ კლება რომ დაიწყო მეორეჯერ მანდ 12:00-18:00 პერიოდში ჭამის შეზღუდვა მივაშველე, მხოლოდ სიარული არ შველოდა

**Comment by KetiBochorishvili** [comment]
ხო, ერთად ძალიან ეფექტურია. მაჩვენე ეგ გრაფიკი ცოტა ხანში კიდევ, იქნებ მეც მომინდეს, მაგრამ მშიერზეც ვერ ვმუშაობ, გულს ვერაფერს ვუდებ. 

ჯერჯერობით ამ ლაპარაკზე მხოლოდ ტორტი გამახსენდა, თეომ გამოაცხო წეღან და მომინდა.

**Comment by KetiBochorishvili** [comment]
state.chosenData-ს და state.chosenTheme-ს ვააფდეითებ, მაგრამ თვითონ dropdown-ში რაც ჩანს ეგ რომ შესაბამისად შევცვალო, ალბათ choices.min.js-ში უნდა ვნახო როგორ ხდება ეგ ჩამოშლილში კონკრეტულ option-ზე დაჭერისას ხო?

**Comment by bumbeishvili** [comment]
> state.chosenData-ს და state.chosenTheme-ს ვააფდეითებ, მაგრამ თვითონ dropdown-ში რაც ჩანს ეგ რომ შესაბამისად შევცვალო, ალბათ choices.min.js-ში უნდა ვნახო როგორ ხდება ეგ ჩამოშლილში კონკრეტულ option-ზე დაჭერისას ხო?

არა, choice item-ზე ხო გაქვს რეფერენსი როცა choice-ს ჰქმნი და წესით მაგას უნდა ჰქონდეს რაიმე მეთოდი რომლითაც შესაძლებელი იქნება რომ მნიშვნელობა შეცვალო.

და დეტალები დოკუმენტაციაში უნდა ჰქონდეთ და მაგაზე მოგიწევს გადახედვა , *.min.js ან ზოგადად სხვა ბიბლიოთეკების ფაილებში ძაან რთულია რომ რამე გაიგო იმდენად განზოგადებულად უწერიათ კოდი და min.js-ი კი ნიშნავს რომ მინიფიცირებულია ზომა, ანუ ცვლადებს სახელები აქვთ შეცვლილი, space-ები წაშლილი აქვთ, შეუძლებელია მანდ რამის გაგება

**Comment by KetiBochorishvili** [comment]
მგონი გავაკეთე, სასიამოვნო იყო ერთი ხაზით რომ მოგვარდა. 

სტილი დავაკოპირე წინა პროექტიდან, რეალურად ხარვეზის გასწორება მინდოდა და ყველაფერი წამოვიღე.

**Comment by bumbeishvili** [comment]
ძაან კაი, ხელის შევლება სჭირდება ცოტა სტილებს და მაგას გავაკეთებ მერე ჩემს ნაწილზე რომ დავიწყებ მუშაობას. 

შენ გაქვს ხო პროექტები ამის გარდა?

**Comment by KetiBochorishvili** [comment]
ხო, სტილებში ძაან უგემოვნო ვარ, მაგრამ თუ რამეა აქ გასაკეთებელი, რასაც შევძლებ მითხარი.

ამ წუთში არაფერი მაქვს, შანკარისთვის მაქვს ნათქვამი 25-დან მეცლებათქო და მაგ დროისთვის შეგეხმიანებით ახალი milestone-ებითო, pie chart რომ მაჩვენეს observable-დან, მაგას გადავხედავ.  შეიძლება მივწერო მცალიათქო, მაგრამ ისედაც ძაან წელავენ ხოლმე ეგენი და რავი, მომცემენ ალბათ როცა ეცლებათ.

**Comment by bumbeishvili** [comment]
თუ გინდა ერთი რთული 500$-იანი job მაქვს,  ბევრი რაღაც არის გასაკეთებელი და მაგრამ პატარა დედლაინი აქვს , 20 მაისამდე , ჯერ გააქტიურებული არ არის , მაგრამ 70%-ით გაააქტიურებს

მოკლედ Sankey არის ერთი და მეორე Heatmap-ი, ორივეზე არსებული კოდი იქნება გადასაკეთებელი. თუ გცალია მაგისთვის დღესვე ჩავწერ ვიდეოს და გეტყვი რა იქნება გასაკეთებელი

**Comment by bumbeishvili** [comment]
ერთის შემთხვევაში ამ ვიზუალიზაციის გადაკეთებაა საჭირო

https://observablehq.com/@bumbeishvili

მეორე შემთხვევაში ამის

https://observablehq.com/@d3/sankey

**Comment by KetiBochorishvili** [comment]
პირველი ლინკი ზოგადად გახსნა. მეორე უფრო ნაცნობია ჩემთვის. 

კი მცალია, მაგრამ რომ ვერ გავიგო და უარესად მოგაცდინო არ მინდა.

**Comment by bumbeishvili** [comment]
შემეშალა პირველი ლინკი - ეს არის 

https://observablehq.com/@bumbeishvili/heatmap-grid

გაგებით გაიგებ დარწმუნებული ვარ, უბრალოდ ჯერ რომ არ დამთანხმებია კლიენტი ეგ მაშფოთებს ცოტა :დ

კარგი მაშინ სავარაუდოდ დღეს ღამე ჩავწერ ვიდეოს რა იქნება ორივე შემთხვევაში გასაკეთებელი

**Comment by KetiBochorishvili** [comment]
რა ლამაზი ჰითმეფია თუ რაცაა. 

მოკლედ, ასეთ სტრესულ დროს არ მინდა დაგაწვე კიდე, თუმცა ამათი სწავლა არ მაწყენდა. 
თუ შენ უფრო მალე გააკეთებ ვიდრე ჩემზე დახარჯავ, მირჩევნია შენ გააკეთო.

**Comment by bumbeishvili** [comment]
არ დამაწვები, პირიქით შემიმსუბუქებ ამ პროექტზე :ს

**Comment by bumbeishvili** [comment]
კარგი გაგიზიარებ მოკლედ repo-ს და იქ ავტვირთავ ვიდეოს, დღეს ღამე ჩავწერ ან ხვალ დილით თუ ძაან დაღლილი ვიქნები

**Comment by KetiBochorishvili** [comment]
კარგი, მადლობა დათო ^_^

**Comment by bumbeishvili** [comment]
გადახედვაც არ გინდა პრინციპსი, ბევრი რაღაც ამოსაკლებია ამ მეორე ვიზუალიზაციიდან 

ერთადერთი რაც შეგიძლია თუ დრო გაქვს დღეს, შეგიძლია მაიკის სანქეის კოდი, ჩვენს კონვენშენზე გადააწყო 

https://observablehq.com/@d3/sankey

სხვა დროსაც დაგჭირდება მსგავსი გადაწყობა

**Comment by bumbeishvili** [comment]
https://github.com/bumbeishvili/bazz4u-keti-heatmap-sankey-modifications/invitations

**Comment by KetiBochorishvili** [comment]
> გადახედვაც არ გინდა პრინციპში, ბევრი რაღაც ამოსაკლებია ამ მეორე (ჩემი) ვიზუალიზაციიდან
> 
> ერთადერთი რაც შეგიძლია თუ დრო გაქვს დღეს, შეგიძლია მაიკის სანქეის კოდი, ჩვენს კონვენშენზე გადააწყო
> 
> https://observablehq.com/@d3/sankey
> 
> სხვა დროსაც დაგჭირდება მსგავსი გადაწყობა

აჰა, ანუ ჩვენი სტრუქტურით რომ დავწერო vs-ში და იმუშავოს ეგ გვინდა ხო? სულ მაფიქრებდა observable-დან კოდის გადმოტანის ამბავი.

**Comment by bumbeishvili** [comment]
ხო, ამოკრება მოგიწევს ნაწილ ნაწილების და ჩვენს კოდში გადმოტანა
